import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from '@/components/ui/button';
import { Link, useNavigate } from 'react-router-dom';
const ProductRow = ({ id, name, price, unit, category, suppliers, status, description, lastUpdated, createdAt }) => {
    const navigate = useNavigate();
    const dateToShow = lastUpdated || createdAt || '';
    const formattedDate = dateToShow ? new Date(dateToShow).toLocaleDateString('es-ES') : '-';
    const handleRowClick = (e) => {
        // Don't navigate if clicking on buttons or links
        if (e.target.closest('button, a')) {
            return;
        }
        navigate(`/product-admin/${id}`);
    };
    return (_jsxs("tr", { className: "border-b border-gray-100 hover:bg-gradient-to-r hover:from-green-50/50 hover:to-emerald-50/50 transition-all duration-200 cursor-pointer", onClick: handleRowClick, children: [_jsxs("td", { className: "px-2 py-2 sm:px-4 sm:py-3 lg:px-6 lg:py-4", children: [_jsx("div", { className: "font-medium text-gray-900 text-sm sm:text-base break-words", children: name }), _jsxs("div", { className: "text-xs text-gray-500 mt-1 space-y-0.5", children: [suppliers.length > 0 && (_jsxs("div", { children: ["Proveedores: ", suppliers.slice(0, 1).join(', '), suppliers.length > 1 && ` +${suppliers.length - 1} más`] })), _jsxs("div", { className: "md:hidden", children: ["Categor\u00EDa: ", _jsx("span", { className: "font-medium", children: category }), unit && _jsxs("span", { className: "ml-2", children: ["\u2022 Unidad: ", unit] })] }), _jsxs("div", { className: "lg:hidden", children: ["Creado: ", createdAt ? new Date(createdAt).toLocaleDateString('es-ES') : '-'] }), _jsxs("div", { className: "lg:hidden", children: ["Actualizado: ", formattedDate] })] })] }), _jsx("td", { className: "px-2 py-2 sm:px-4 sm:py-3 lg:px-6 lg:py-4", children: _jsx("div", { className: "text-sm sm:text-base font-semibold text-gray-900", children: price != null ? `$${Number(price).toLocaleString()}` : 'N/A' }) }), _jsx("td", { className: "hidden md:table-cell px-2 py-2 md:px-4 md:py-3 lg:px-6 lg:py-4", children: _jsx("div", { className: "text-xs sm:text-sm text-gray-600", children: unit || 'N/A' }) }), _jsx("td", { className: "hidden md:table-cell px-2 py-2 md:px-4 md:py-3 lg:px-6 lg:py-4", children: _jsx("span", { className: "inline-flex items-center px-2 sm:px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800 break-words", children: category }) }), _jsx("td", { className: "hidden lg:table-cell px-2 py-2 lg:px-6 lg:py-4", children: _jsx("div", { className: "text-xs sm:text-sm text-gray-600", children: createdAt ? new Date(createdAt).toLocaleDateString('es-ES') : '-' }) }), _jsx("td", { className: "hidden lg:table-cell px-2 py-2 lg:px-6 lg:py-4", children: _jsx("div", { className: "text-xs sm:text-sm text-gray-600", children: formattedDate }) }), _jsx("td", { className: "hidden lg:table-cell px-2 py-2 lg:px-6 lg:py-4", children: description ? (_jsx("div", { className: "text-xs sm:text-sm text-gray-600 max-w-xs truncate", title: description, children: description })) : (_jsx("div", { className: "text-xs sm:text-sm text-gray-400", children: "Sin descripci\u00F3n" })) }), _jsx("td", { className: "px-2 py-2 sm:px-4 sm:py-3 lg:px-6 lg:py-4", children: _jsx("div", { className: "flex gap-x-1 sm:gap-x-2", children: _jsx(Link, { to: `/product-admin/${id}`, children: _jsx(Button, { size: "sm", variant: "outline", className: "border-green-200 text-green-700 hover:bg-green-50 hover:border-green-300 text-xs sm:text-sm px-2 sm:px-3 py-1 sm:py-2", children: "Ver" }) }) }) })] }));
};
export default ProductRow;
