import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
const SupplierSearchBar = ({ name, contact, email, onNameChange, onContactChange, onEmailChange, }) => {
    return (_jsxs("div", { className: "space-y-3 sm:space-y-4", children: [_jsx("div", { className: "flex items-center space-x-2 sm:space-x-3 mb-3 sm:mb-4", children: _jsxs("div", { className: "flex items-center space-x-2 text-green-700", children: [_jsx("svg", { className: "w-4 h-4 sm:w-5 sm:h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" }) }), _jsx("span", { className: "font-semibold text-sm sm:text-base", children: "Buscar y Filtrar Proveedores" })] }) }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3 sm:gap-4", children: [_jsxs("div", { className: "space-y-1 sm:space-y-2", children: [_jsx("label", { className: "text-xs sm:text-sm font-medium text-gray-700", children: "Nombre del Proveedor" }), _jsx(Input, { placeholder: "Buscar por nombre...", value: name, onChange: e => onNameChange(e.target.value), className: "border-gray-300 focus:border-green-500 focus:ring-green-500 bg-white text-gray-900 text-sm sm:text-base px-2 sm:px-3 py-1 sm:py-2" })] }), _jsxs("div", { className: "space-y-1 sm:space-y-2", children: [_jsx("label", { className: "text-xs sm:text-sm font-medium text-gray-700", children: "Contacto" }), _jsx(Input, { placeholder: "Buscar por contacto...", value: contact, onChange: e => onContactChange(e.target.value), className: "border-gray-300 focus:border-green-500 focus:ring-green-500 bg-white text-gray-900 text-sm sm:text-base px-2 sm:px-3 py-1 sm:py-2" })] }), _jsxs("div", { className: "space-y-1 sm:space-y-2", children: [_jsx("label", { className: "text-xs sm:text-sm font-medium text-gray-700", children: "Email" }), _jsx(Input, { placeholder: "Buscar por email...", value: email, onChange: e => onEmailChange(e.target.value), className: "border-gray-300 focus:border-green-500 focus:ring-green-500 bg-white text-gray-900 text-sm sm:text-base px-2 sm:px-3 py-1 sm:py-2" })] })] }), (name || contact || email) && (_jsxs("div", { className: "flex flex-col sm:flex-row sm:items-center sm:justify-between pt-3 sm:pt-4 border-t border-gray-200 gap-2 sm:gap-0", children: [_jsxs("div", { className: "flex items-center space-x-2 text-xs sm:text-sm text-gray-600", children: [_jsx("svg", { className: "w-3 h-3 sm:w-4 sm:h-4", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 100 4m0-4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 100 4m0-4v2m0-6V4" }) }), _jsx("span", { children: "Filtros activos aplicados" })] }), _jsx(Button, { variant: "outline", size: "sm", onClick: () => {
                            onNameChange('');
                            onContactChange('');
                            onEmailChange('');
                        }, className: "text-gray-600 border-gray-300 hover:bg-gray-50 text-xs sm:text-sm px-2 sm:px-3 py-1 sm:py-2 w-full sm:w-auto", children: "Limpiar Filtros" })] }))] }));
};
export default SupplierSearchBar;
