import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useNavigate } from 'react-router-dom';
const SuppliersTable = ({ suppliers }) => {
    const navigate = useNavigate();
    const handleSupplierClick = (supplierId) => {
        navigate(`/supplier-admin/${supplierId}`);
    };
    return (_jsxs(Card, { className: "shadow-lg border-0 rounded-xl overflow-hidden", children: [_jsx("div", { className: "bg-gradient-to-r from-gray-50 to-green-50 border-b border-green-100 p-3 sm:p-4 md:p-6", children: _jsxs("h3", { className: "text-lg sm:text-xl font-semibold text-gray-900 flex items-center", children: [_jsx("svg", { className: "w-4 h-4 sm:w-5 sm:h-5 mr-2 text-green-600", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" }) }), _jsx("span", { className: "text-sm sm:text-lg", children: "Proveedores" }), _jsxs("span", { className: "ml-2 text-xs sm:text-sm font-normal text-gray-500", children: ["(", suppliers.length, ")"] })] }) }), _jsx("div", { className: "p-3 sm:p-4", children: suppliers.length === 0 ? (_jsx("div", { className: "text-center py-6 sm:py-8 text-gray-500", children: _jsxs("div", { className: "flex flex-col items-center justify-center", children: [_jsx("div", { className: "w-10 h-10 sm:w-12 sm:h-12 mb-3 sm:mb-4 bg-gray-100 rounded-full flex items-center justify-center", children: _jsx("svg", { className: "w-5 h-5 sm:w-6 sm:h-6 text-gray-400", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" }) }) }), _jsx("p", { className: "font-medium text-sm sm:text-base", children: "No se encontraron proveedores" }), _jsx("p", { className: "text-xs sm:text-sm text-gray-400 mt-1", children: "No hay proveedores vinculados a este producto" })] }) })) : (_jsx("div", { className: "space-y-3 sm:space-y-4", children: suppliers.map((supplier, index) => (_jsxs("div", { className: `p-3 sm:p-4 rounded-lg border border-gray-200 hover:border-green-300 hover:bg-gradient-to-r hover:from-green-50/30 hover:to-emerald-50/30 transition-all duration-200 ${index % 2 === 0 ? 'bg-white' : 'bg-gray-50/30'}`, children: [_jsxs("div", { className: "flex flex-col sm:flex-row sm:items-center sm:justify-between mb-2 sm:mb-3 gap-2 sm:gap-0", children: [_jsx("h4", { className: "font-semibold text-gray-900 hover:text-green-700 cursor-pointer transition-colors duration-200 text-sm sm:text-base break-words", onClick: () => handleSupplierClick(supplier.id), children: supplier.name || 'Proveedor Desconocido' }), _jsx("span", { className: `inline-flex items-center px-2 sm:px-2.5 py-0.5 rounded-full text-xs font-medium self-start sm:self-auto ${supplier.is_active
                                            ? 'bg-green-100 text-green-800'
                                            : 'bg-gray-100 text-gray-800'}`, children: supplier.is_active ? 'Activo' : 'Inactivo' })] }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 sm:gap-4 text-xs sm:text-sm", children: [_jsxs("div", { children: [_jsx("span", { className: "text-gray-500 block sm:inline", children: "Precio:" }), _jsx("div", { className: "font-semibold text-gray-900 mt-1 sm:mt-0 sm:ml-1 sm:inline", children: supplier.price != null ? `$${Number(supplier.price).toLocaleString()}` : 'N/A' })] }), _jsxs("div", { children: [_jsx("span", { className: "text-gray-500 block sm:inline", children: "Stock:" }), _jsxs("div", { className: `font-medium mt-1 sm:mt-0 sm:ml-1 sm:inline ${(supplier.stock || 0) > 50 ? 'text-green-600' :
                                                    (supplier.stock || 0) > 10 ? 'text-yellow-600' : 'text-red-600'}`, children: [supplier.stock != null ? supplier.stock : 0, " unidades"] })] }), _jsxs("div", { className: "sm:col-span-1 lg:col-span-1", children: [_jsx("span", { className: "text-gray-500 block sm:inline", children: "Tiempo de Entrega:" }), _jsxs("div", { className: "font-medium text-gray-900 mt-1 sm:mt-0 sm:ml-1 sm:inline", children: [supplier.lead_time_days != null ? supplier.lead_time_days : 0, " d\u00EDas"] })] })] }), _jsx("div", { className: "mt-3 pt-3 border-t border-gray-100", children: _jsx(Button, { size: "sm", variant: "outline", onClick: () => handleSupplierClick(supplier.id), className: "w-full border-green-200 text-green-700 hover:bg-green-50 text-xs sm:text-sm px-2 sm:px-3 py-1 sm:py-2", children: "Ver Detalles" }) })] }, supplier.id))) })) })] }));
};
export default SuppliersTable;
